### ISSUE TITLE
[BUG] Chat is not responding to commands, but server console does

### ISSUE THREAD

**Issue by K4ryuu** [roflmuffin/CounterStrikeSharp#93]
So basically, I've encountered a weird bug, which is appeared only on one server of the several, which I was checking on. First I was thinking about that possibly some leftover from meta plugins or so, which is incompatible with CSS, so I installed freshly the server, added Metamod dev2 and css latest (v53). When I installed a test plugin to check the problem again it does the following:

- If you use the command (which is registered) in the chat, it just simply send "!test" to the chat as message.
- If you use the command in server console, the command is executed properly.

I tried to check this on multiple dev servers from multiple hosts, but so far I see this bug only on one and first server so far.

**Comment by roflmuffin** [comment]
Could be an encoding issue, do you know if this server is in a different locale? Might need more repro information

**Comment by K4ryuu** [comment]
This server is hosted in Romania as I know, so my guess is that. However I'm going to contact the owner when he's available again. If you have any exact questions about the host where they rent the server I forward them and they contact their support with those questions.

**Comment by roflmuffin** [comment]
They could try running with invariant culture on .net side and see if this makes any difference? Otherwise it might be on the C++ side.

`DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=true`

**Comment by K4ryuu** [comment]
I've added `"System.Globalization.Invariant": true` to the runtimeconfig's configProperties, but that didn't make any difference sadly.

**Comment by sphaxa** [comment]
also seeing this issue on my end, went from v50 to v54 and latest metamod. No other changes. Now (!) commands do not work at all. (/) commands and console command work perfectly fine.

**Comment by K4ryuu** [comment]
I fixed the problem on my end, though I forgot to update you here. I had been testing it for two days and eventually, I exported the .cs and .csproj files. Then, I created a new project using the dotnet command. Strangely, the new solution file ended up having the same IDs as the old ones, which was quite puzzling. It seemed like the new project somehow "restored" the old project's IDs and solutions, including their files, into different folders on my Mac.

After several attempts, I managed to generate a project with different values, and the old project files were not included in it. After making these changes, everything started working again. I'm not entirely sure if this was the solution, but the issue resolved itself somehow over the course of two days, and now the server can execute those commands just like all the other projects.

I hope this clarifies the situation. If you have any further questions or need additional assistance, please feel free to ask.

**Comment by miguno** [comment]
Same problem here with CSS 1.0.54 and latest Metamod (v1266).

**Comment by miguno** [comment]
> Strangely, the new solution file ended up having the same IDs as the old ones, which was quite puzzling.

Which IDs are you referring to?

**Comment by sphaxa** [comment]
Additional context, server is on linux. Tried setting invariant and it didn't fix anything. coreconfig is loading correctly and is using the correct version.

I swapped the triggers, ! for silent and / for public. And it appears that whatever is set to a silent trigger is working fine. But whatever character I set to be public do not work.

ALSO, if I add additional characters to the public trigger, ex [ "!", "."] then the server will segfault when either of them are used, instead of just nothing happening.

Im busy with work atm but can try and repro and get dumps later if needed.

**Comment by roflmuffin** [comment]
Would you be able to run CS2 with SPDLOG_LEVEL env set to "trace", i.e. "SPDLOG_LEVEL=trace ./CS2". This should provide more logging to debug

**Comment by chenbuyi2019** [comment]
I am having this problem too . 
I updated to v55 last hour. and i found all chat commands are not working in chats, the console part is still working.
For example: `css` and `!css` .
when i type `!css` in client chat, it didnt tell me "[CSS] You do not have..."   
but if i type `css` in client console,it works and prints  "[CSS] You do not have..." in my chatbox.

I downgrade to v53, the chat part works again.   
my server version: `1.39.7.2/13972`  
my os: `Windows 10,11`

**Comment by audiomaster99** [comment]
In downgraded from v54 to v53, and had core.json from v54 which was like this `"PublicChatTrigger": [ "!" ],` after I deleted [] chat commands started working, but if I do that in v54 or v55 i get this error:
`CSSharp: Could not read '/home/container/game/csgo/addons/counterstrikesharp/configs/core.json'. Error: Failed to parse CoreConfig file: [json.exception.type_error.302] type must be array, but is string`

**Comment by roflmuffin** [comment]
This should be fixed now as part of v56 release. Please try this build and confirm and I will close this issue.

**Comment by audiomaster99** [comment]
> This should be fixed now as part of v56 release. Please try this build and confirm and I will close this issue.

Chat commands do work in v56

**Comment by Sidroz** [comment]
I still can't use commands with "!" only with "/"
